#!/bin/bash
# Build a compressed bootable disk image from the live-build chroot.
# Output is a zstd-compressed raw disk image that install_to_disk.sh
# dd's onto the target during appliance install. This is the same
# pattern pfSense / OPNsense / Proxmox use — the installer never
# runs grub-install or update-grub on the target at install time;
# the image is pre-built, tested, and sealed.
#
# Usage:
#   build_golden_image.sh <chroot-dir> <out-img.zst>
set -euo pipefail

CHROOT="${1:?chroot dir required}"
OUT="${2:?output .img.zst path required}"
SIZE="${GOLDEN_SIZE:-6G}"
WORK="$(mktemp -d /tmp/brainrot-golden.XXXXXX)"
RAW="$WORK/golden.img"

trap 'cleanup' EXIT
cleanup() {
    set +e
    mountpoint -q "$WORK/mnt/dev/pts" && umount "$WORK/mnt/dev/pts"
    mountpoint -q "$WORK/mnt/dev"     && umount "$WORK/mnt/dev"
    mountpoint -q "$WORK/mnt/proc"    && umount "$WORK/mnt/proc"
    mountpoint -q "$WORK/mnt/sys"     && umount "$WORK/mnt/sys"
    mountpoint -q "$WORK/mnt/boot/efi" && umount "$WORK/mnt/boot/efi"
    mountpoint -q "$WORK/mnt"         && umount "$WORK/mnt"
    [ -n "${LOOP:-}" ] && losetup -d "$LOOP" 2>/dev/null
    rm -rf "$WORK"
}

echo "[golden] Building $OUT from $CHROOT (size $SIZE)..."

truncate -s "$SIZE" "$RAW"

# Partition table: GPT with BIOS-boot + ESP + root
parted -s "$RAW" mklabel gpt
parted -s "$RAW" mkpart BIOS-boot 1MiB 2MiB
parted -s "$RAW" set 1 bios_grub on
parted -s "$RAW" mkpart ESP fat32 2MiB 514MiB
parted -s "$RAW" set 2 esp on
parted -s "$RAW" set 2 boot on
parted -s "$RAW" mkpart root ext4 514MiB 100%

LOOP=$(losetup --show -fP "$RAW")
partprobe "$LOOP"
udevadm settle

ESP_DEV="${LOOP}p2"
ROOT_DEV="${LOOP}p3"

mkfs.vfat -F32 -n ESP "$ESP_DEV" >/dev/null
mkfs.ext4 -F -L brainrot-root "$ROOT_DEV" >/dev/null

ESP_UUID=$(blkid -s UUID -o value "$ESP_DEV")
ROOT_UUID=$(blkid -s UUID -o value "$ROOT_DEV")

MNT="$WORK/mnt"
mkdir -p "$MNT"
mount "$ROOT_DEV" "$MNT"
mkdir -p "$MNT/boot/efi"
mount "$ESP_DEV" "$MNT/boot/efi"

echo "[golden] Syncing chroot..."
rsync -aAXH \
    --exclude='/proc/*' \
    --exclude='/sys/*' \
    --exclude='/dev/*' \
    --exclude='/run/*' \
    --exclude='/tmp/*' \
    --exclude='/mnt/*' \
    --exclude='/media/*' \
    --exclude='/boot/efi/*' \
    --exclude='/binary' \
    --exclude='/binary.hybrid.iso' \
    --exclude='/binary.sh' \
    --exclude='/opt/brainrot-install' \
    "$CHROOT/." "$MNT/"

cat > "$MNT/etc/fstab" <<FSTAB
# /etc/fstab: static file system information. Generated by
# build_golden_image.sh at ISO build time.
UUID=$ROOT_UUID  /          ext4  errors=remount-ro  0 1
UUID=$ESP_UUID   /boot/efi  vfat  umask=0077        0 1
FSTAB

# Purge casper so we boot as a normal installed system.
chroot "$MNT" env DEBIAN_FRONTEND=noninteractive \
    apt-get -y purge casper 2>&1 | tail -3 || true

# Casper leaves a "(live)" PS1 marker in /etc/bash.bashrc (and skel)
# that survives a plain purge — remove any trace so an installed
# appliance never displays (live)@... at a shell prompt.
for f in "$MNT/etc/bash.bashrc" "$MNT/etc/skel/.bashrc" "$MNT/root/.bashrc"; do
    if [ -f "$f" ]; then
        sed -i '/(live)/d' "$f" 2>/dev/null || true
    fi
done
# And any leftover casper scripts in profile.d.
rm -f "$MNT"/etc/profile.d/*casper* "$MNT"/etc/profile.d/*live-installer* 2>/dev/null || true

# MODULES=most — initramfs carries every available storage driver
# so the image boots on any hardware (Hyper-V, KVM, bare metal, ...).
if [ -f "$MNT/etc/initramfs-tools/initramfs.conf" ]; then
    sed -i 's/^MODULES=.*/MODULES=most/' "$MNT/etc/initramfs-tools/initramfs.conf"
fi

mount --bind /dev     "$MNT/dev"
mount --bind /dev/pts "$MNT/dev/pts"
mount -t proc  proc   "$MNT/proc"
mount -t sysfs sys    "$MNT/sys"

chroot "$MNT" update-initramfs -u -k all 2>&1 | tail -3

echo "[golden] Installing GRUB (UEFI named + BIOS)..."
chroot "$MNT" grub-install \
    --target=x86_64-efi \
    --efi-directory=/boot/efi \
    --bootloader-id=BrainrotFilter \
    --no-nvram \
    --recheck --no-floppy 2>&1 | tail -3

chroot "$MNT" grub-install \
    --target=i386-pc \
    --recheck --no-floppy "$LOOP" 2>&1 | tail -3

chroot "$MNT" update-grub 2>&1 | tail -3

# Fallback /EFI/BOOT/BOOTX64.EFI + grub.cfg stubs in both dirs.
mkdir -p "$MNT/boot/efi/EFI/BOOT"
if [ -f "$MNT/boot/efi/EFI/BrainrotFilter/shimx64.efi" ]; then
    cp "$MNT/boot/efi/EFI/BrainrotFilter/shimx64.efi" "$MNT/boot/efi/EFI/BOOT/BOOTX64.EFI"
    cp "$MNT/boot/efi/EFI/BrainrotFilter/grubx64.efi" "$MNT/boot/efi/EFI/BOOT/grubx64.efi"
else
    cp "$MNT/boot/efi/EFI/BrainrotFilter/grubx64.efi" "$MNT/boot/efi/EFI/BOOT/BOOTX64.EFI"
fi

for d in "$MNT/boot/efi/EFI/BrainrotFilter" "$MNT/boot/efi/EFI/BOOT"; do
    cat > "$d/grub.cfg" <<EOF
# Stage-1 stub: locate the real /boot/grub/grub.cfg by the root UUID
# burned at build time and hand off.
search --no-floppy --fs-uuid --set=root $ROOT_UUID
set prefix=(\$root)/boot/grub
configfile /boot/grub/grub.cfg
EOF
done

# Clean apt cache so the image compresses tighter.
chroot "$MNT" apt-get clean 2>&1 | tail -1 || true
rm -rf "$MNT/var/lib/apt/lists"/*

# Unmount cleanly.
umount "$MNT/dev/pts"
umount "$MNT/dev"
umount "$MNT/proc"
umount "$MNT/sys"
umount "$MNT/boot/efi"
umount "$MNT"

# Zero unused space so compression is maximal.
echo "[golden] Zeroing free space..."
mount "$ROOT_DEV" "$MNT"
dd if=/dev/zero of="$MNT/.zero-fill" bs=1M status=none conv=fdatasync 2>/dev/null || true
rm -f "$MNT/.zero-fill"
umount "$MNT"

losetup -d "$LOOP"
LOOP=""

echo "[golden] Compressing to $OUT ..."
mkdir -p "$(dirname "$OUT")"
zstd -19 --long=27 -f "$RAW" -o "$OUT"
rm -f "$RAW"

echo "[golden] Done: $OUT ($(du -h "$OUT" | cut -f1))"
